image: golang:1.12

stages:
  - build
  - test
  - deploy

variables:
  APP_NAME: katabot

build:
  stage: build
  script:
    - go mod download
    - go build

test:
  stage: test
  script:
    - go test

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
  only:
    - master
  script:
    - git-push ssh://dokku@$DOKKU_HOST:22/$APP_NAME
